version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  build_and_test:  # Ensure this name matches the one used in your workflow
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: Change directory and Install Dependencies
          command: |
            cd UI_test
            npm install
      - browser-tools/install-browser-tools
      - run:
          name: Run Nightwatch Tests
          command: |
            cd UI_test
            npx nightwatch

workflows:
  your-workflow:
    jobs:
      - build_and_test  # This name must match the job name defined above
