version: 2.1

jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:lts'
    working_directory: ../../UI_test
    steps:
      - checkout
      - run:
    name: List directory contents
    command: ls -la ~/

      - run: npm install
      - run: npx nightwatch

workflows:
  build_and_test_workflow:
    jobs:
      - build-and-test
