version: 2.1

jobs:
  build-and-test:
    docker:
      - image: selenium/standalone-chrome:latest  # Use the latest version or specify a specific tag
    steps:
      - checkout
      - run:
          name: Install Node.js (Version 14.x)
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version

      - run:
          name: Install Project Dependencies
          command: |
            # Assuming your project uses Node.js
            # Install Node.js in the container
            sudo apt-get update && sudo apt-get install -y nodejs npm
            # Navigate to your test directory and install dependencies
            cd UI_test
            npm install
      - run:
          name: Run Tests
          command: |
            cd UI_test
            npx nightwatch

workflows:
  build_and_test_workflow:
    jobs:
      - build-and-test
