version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  build:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install Project Dependencies
          command: |
            # Assuming your project uses Node.js
            # Install Node.js in the container
            sudo apt-get update && sudo apt-get install -y nodejs npm
            # Navigate to your test directory and install dependencies
            cd UI_test
            npm install
      - run:
          name: Run Tests
          command: |
            cd UI_test
            npx nightwatch

workflows:
  build_and_test_workflow:
    jobs:
      - build-and-test
