jobs:
  build-and-test:
    docker:
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run:
          name: Install Node.js (Version 16.x)
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version
      - run:
          name: Install Project Dependencies
          command: |
            # No need to install Node.js and npm again since they were installed in the previous step.
            # Navigate to your test directory and install dependencies.
            cd UI_test
            npm install
      - run:
          name: Run Tests
          command: |
            cd UI_test
            npx nightwatch
