version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - checkout


      - run:
          name: Verify Chrome Installation
          command: google-chrome --version
   
      - run:
          name: Install dependencies and run tests
          command: |
            cd UI_test
            npm install
            npx nightwatch

workflows:
  build_and_test_workflow:
    jobs:
      - build-and-test
